#!/usr/bin/env bash
# A script that Installs and configure's HAproxy on your lb-01 server
sudo apt update -y
sudo apt install haproxy -y
echo "frontend main
	bind *:80
	mode http
	default_backend servers
backend servers
	balance roundrobin
	server 80613-web-01 18.235.248.178:80 check
	server 80613-web-02 54.160.121.36:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
