#!/usr/bin/env bash
# A Bash script that displays Best School 10 times using while loop
# but for the 9th iteration, displays Best School and then Hi on a new line.

r=0
while [ $r -lt 10 ]
do
 if [ $r -eq 9 ]
 then
  echo "Hi"
 fi 
 echo "Best School"
 ((r++))
done
