#!/usr/bin/env bash
# a script that loops from 1 to 10
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

r=0
while [ $r -lt 10 ]
do
 if [ $r -eq 3 ]
 then
  echo "bad luck"
 elif [ $r -eq 7 ]
 then
  echo "good luck"
 else
  echo "Best School"
 fi
 ((r++))
done
