#!/usr/bin/env bash
# a script that loops from 1 to 20
# displays 4 and then bad luck from China for the 4th loop iteration
# isplays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

r=1
while [ $r -le 20 ]
do
 echo "$r"
 case $r in
  "4") echo "bad luck from china";;
  "9") echo "bad luck from japan";;
  "17") echo "bad luck from italy"
 esac
 ((r++))
done
